### ISSUE TITLE
Adding version number to asset/viewer.js makes resolution a pain

### ISSUE THREAD

**Issue by jpike88** [stephanrauh/ngx-extended-pdf-viewer#641]
I had a direct reference to the viewer as follows:

```import 'ngx-extended-pdf-viewer/assets/viewer-es5.js';```

This is because I want to lazy load it in my app.
After updating to a recent version, my reference is broken because now the file is:

```import 'ngx-extended-pdf-viewer/assets/viewer-2.6.423-es5.min.js';```

Now whoever the viewer is updated in the future, it's going to break my import reference again. can it just go back to ```viewer.js```?

**Comment by stephanrauh** [comment]
Just omit the import statement. I've implemented lazy loading some time ago. You only need the import if you want to do the opposite thing: eager loading.

Actually, the lazy loading approach I've implemented has another advantage. If you're using a modern browser, it loads the ES2015 version of the three JavaScript classes. This version is faster and smaller than the ES5 version, which is only needed for IE11 and several mobile devices running old versions of the operating system.

Can you run a test and tell me if it works, please?

**Comment by jpike88** [comment]
seems to work good, thanks!

**Comment by jpike88** [comment]
actually bad news, I was talking out my ass because tests passed but that didn't mean it actually worked.

I use fuse-box bundler which is fast as lightning, but the downside is that I have to explicitly reference files in import statements in order for them to get pulled in (which is why I had it that way to start)... the original issue still stands unfortunately.

**Comment by jpike88** [comment]
I don't even know if there's a sane way around this, I have to take things one step further and copy those files out and modify them etc... best to just cover my method with an end to end test and call it a day

**Comment by stephanrauh** [comment]
@jpike88 This one? Do you recommend it?

As for your question: Don't give up so easily - there are still a couple of options we haven't tried. For instance, I guess you're using npm? So you can add a post-install or pre-compile script to your package.json that copies the viewer-*-es5.min.js to your assets folder and renames it to viewer-es5.min.js.

**Comment by jpike88** [comment]
not using npm, I use fusebox (fuse.js script in root dir). In the meantime I've just pulled out a copy of the files into a separate assets folder and referenced manually from index.html.

It would be nice to have those files packaged themselves in a separate npm repo, but this works
