### ISSUE TITLE
enablePinchOnMobile set to true causes undesirable zoom issues

### ISSUE THREAD

**Issue by adambeer** [stephanrauh/ngx-extended-pdf-viewer#918]
When enabling the enablePinchOnMobile and zooming in and out, there are a couple issues that are happening:

- After finishing a pinch to zoom gesture sometimes the pdf will jump to an entirely different page than was being zoomed on
- After starting/finishing a pinch gesture, the positioning of the page sometimes becomes jerky

I have tested this using an iphone. Every document I tested had this issue but just in case, here is a document that can be used to replicate this: [Transport Canada AIM](https://tc.canada.ca/sites/default/files/2021-03/aim_2021-1_access_e.pdf)

I am using version 9 of the library with pdf.js 2.9. Thanks for all of your help with this library, its awesome!

**Comment by stephanrauh** [comment]
I know I'm demanding a lot, but I'm afraid I need your help. During the last couple of weeks, more issues come in than I can answer. Would you mind to help me hunting down the bug?

`enablePinchOnMobile` is implemented in a class called `PinchOnMobileSupport`. It's loosely coupled to ngx-extended-pdf-viewer, so you can easily override it with your own copy. I can help you if necessary, but the basic idea is not to set `enablePinchOnMobile="true"` but to instantiate your own copy of `PinchOnMobileSupport`. That's exactly what ngx-extended-pdf-viewer does (https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/03c9bfce672a60f0ebe5edacc160a23c5cbba753/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer.component.ts#L881).

Now you can debug the pinch gesture support. I'm afraid that's not enough to solve your issue. It's probably a complex interaction with pdf.js itself. The only hint I can give you is to set `[minifiedJSLibraries]=false`.

Best regards,
Stephan

**Comment by stephanrauh** [comment]
@adambeer Is your bug related to #672?

**Comment by adambeer** [comment]
@stephanrauh Ill take a deeper look at this and yes, from the video in #672 it looks like the identical issue Im having. Its just not limited to the last page like that bug report is suggesting.

**Comment by adambeer** [comment]
@stephanrauh I needed zooming capabilities in my app so I added a + and - button and created some methods to zoom in and out in fixed amounts. Even with manually setting the zoom parameter this way, there is still the jumping to different pages issue so that tells me this isnt necessarily related to enablePinchOnMobile.

**Comment by stephanrauh** [comment]
OK, that's probably good news. For some reason unknown, my Macbook doesn't connect to my iPad, so I can't use the debugger. If we can reproduce the bug on the desktop, my life is a lot easier. Or your life, if you want to give it a try yourself.

Unfortunately, I'm afraid the bug lurks in the depth of the pdf.js code. Probably it's related to the method `scrollIntoView()`, but that' just a guess.

**Comment by adambeer** [comment]
@stephanrauh I am trying to test the current version of the library to see is this issue is somehow solved before I jump into code and am having trouble getting it to start. I ran _npm install_ and _ng start_ but Im getting a bunch of errors. I needed to install @angular/material to get it to work as well. Am I missing any steps to just get this running?

**Comment by stephanrauh** [comment]
@adambeer What are you doing precisely? A simple "npm install ngx-extended-pdf-viewer" doesn't require you to add Angular Material. If it does, something's run havoc yesterday when I published the latest version. But maybe you've tried something different?

**Comment by adambeer** [comment]
@stephanrauh I copied the current code off the main branch, ran "npm install" and then "ng start --host 0.0.0.0" to try to test the current version of main to see if this zoom issue somehow got resolved since 2.9.

**Comment by stephanrauh** [comment]
In other words, you've tried to compile the library from source. Did I guess correctly?

I've published my latest changes yesterday as version 10.0.1, so currently, you don't need the source code version. But if you want to use it, use and modify the `npm run showcase` script of the `package.json`. When I'm developing the library, I simply copy the dist folder of the library to the `node_modules` folder of the target application.

If you want to modify the base library, pdf.js, too, things become even more convoluted. I've tried to document my workflow here: https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/main/projects/ngx-extended-pdf-viewer/how-to-build.md

BTW, I hope to find a more efficient workflow soon. Recently, progress has slowed down a lot because every change of pdf.js takes five minutes to compile until I can test it.

**Comment by adambeer** [comment]
@stephanrauh I guess I am. I dont really need to compile from source right now but Im also not familiar how to use the library without it being a "release". 

All im trying to do is modify "src/app/app.component.html" and .ts and build/start it to test pdf.js 2.10 and the latest changes reflected on github. Im downloading this code as a zip, extract it, run npm install, and then try to run the start script.

Im getting errors like:

Module not found: Error: Can't resolve '@angular/material/dialog'
Cannot find module '@angular/material' or its corresponding type declarations.
Can't bind to 'src' since it isn't a known property of 'ngx-extended-pdf-viewer'.
Can't bind to 'showZoomButtons' since it isn't a known property of 'ngx-extended-pdf-viewer'.

**Comment by stephanrauh** [comment]
I see. I've neglected the default project of ngx-extended-pdf-viewer. When I began the project, there was a library in the folder `/projects/ngx-extended-pdf-viewer` and a default project in the root folder. I used the default project to test the library. At some point in time, I created the showcase. Before long, I neglected the default project, using the showcase exclusively to test and develop the features.

So forget about `src/app/app.component.html`. Clone the showcase instead. It's the current reference project.

It's high time I update or delete the default project!

**Comment by adambeer** [comment]
@stephanrauh I dont know whats going on but I cloned the showcase and ran _npm install_ and Im still getting errors. 

`./src/app/extended-pdf-viewer/export/export.component.ts:2:0-144 - Error: Module not found: Error: Can't resolve '../../../../../ngx-extended-pdf-viewer/projects/ngx-extended-pdf-viewer/src/lib/options/pdf-default-options' in 'D:\Test\Repos\default-pdf-viewer2\src\app\extended-pdf-viewer\export'

Error: src/app/extended-pdf-viewer/export/export.component.ts:3:35 - error TS2307: Cannot find module '../../../../../ngx-extended-pdf-viewer/projects/ngx-extended-pdf-viewer/src/lib/options/pdf-default-options' or its corresponding type declarations.

3 import { pdfDefaultOptions } from '../../../../../ngx-extended-pdf-viewer/projects/ngx-extended-pdf-viewer/src/lib/options/pdf-default-options';`

I ran the prestart script, and start2. Any ideas?

**Comment by adambeer** [comment]
@stephanrauh I finally got it running! Is the showcase safe to build something for production exactly the way release 2.9 was setup? I want to test this in place of the 2.9 release version to see if the zooming issues are magically fixed.

**Comment by adamabdulaev** [comment]
Hi. I struggled with this bug for a while too, and now I had to go back to it again. I suspect that it lies in these lines. If you comment them out, there is no scrolling to a completely different page. 
![image](https://user-images.githubusercontent.com/84326043/136176049-4368800f-bde5-4ef8-932e-e59ae3a1562e.png)

**Comment by adamabdulaev** [comment]
I have an opinion that the matter is in the calculations. After the increase, the scroll height changes in pixels, and container.scrollTop stores the value that was before the increase. I checked this with alert (container.scrollTop);

**Comment by adamabdulaev** [comment]
here are some of my attempts to fix the bug. I don't understand why the first alert gives the correct value, and the second one dumps it. Any ideas?
![image](https://user-images.githubusercontent.com/84326043/136235852-38d2e0f0-dd97-454c-88c8-743046174a3f.png)
![photo_2021-10-06_18-31-16](https://user-images.githubusercontent.com/84326043/136236104-b6825b13-a5fe-4586-b66b-9f409d0e1593.jpg)
![photo_2021-10-06_18-31-32](https://user-images.githubusercontent.com/84326043/136236154-afba141c-b66a-403b-80cd-f9dfe15a433a.jpg)

**Comment by adambeer** [comment]
@adamabdulaev When I was playing with just manually adjusting the zoom parameter, I was also getting the same jumping effect you posted on your video in the other ticket. I dont think this bug is limited to pinch to zoom, rather its related to zooming as a whole.

**Comment by adamabdulaev** [comment]
> @adamabdulaev When I was playing with just manually adjusting the zoom parameter, I was also getting the same jumping effect you posted on your video in the other ticket. I dont think this bug is limited to pinch to zoom, rather its related to zooming as a whole.

in my pdf.js implementation in angular i am not using ngx-extended-pdf-viewer. And with enthusiasm for the + and - buttons, this problem is not. But I am using pinchzoom from ngx-extended-pdf-viewer and after scaling the viewerContainer scrolls a few pages up. It seems to me that these are different problems.

**Comment by adambeer** [comment]
@adamabdulaev @stephanrauh Any updates on this?

**Comment by cverons** [comment]
Hi,

I came from :
https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/b3cc11013499b76964924b1b911faee99890a099/projects/ngx-extended-pdf-viewer/src/lib/pinch-on-mobile-support.ts#L98-L103

to :
``` typescript
    const container = document.getElementById('viewerContainer') as HTMLDivElement;
    const dx = this.startX * (this.pinchScale - 1);
    const dy = this.startY * (this.pinchScale - 1);
    container.scrollLeft += dx;
    container.scrollTop += dy;
```
Now, the zoom stays where I left it at the end of the pinch.
As I am managing the paging by my own, I didn't check why it jumps to another page.

@barnewsapp, how about your PR ?
Do you think that you can provide us with a fix in the coming days ?

**Comment by barnewsapp** [comment]
@cverons Hi. I will be working on it this week but I do not expect to have a PR ready this week. 
Maybe next week, but no promises. 
It seems every time I start working on it, some other project gets in the way :-p

**Comment by adambeer** [comment]
@barnewsapp Any updates on this?

**Comment by barnewsapp** [comment]
Hi. I worked about 25 hours on this last week. 

It is more complicated than I first expected. 
But I have made som progress and will do more work this week. 

My version of  pinch-on-mobile-support.ts-file is currency 563 lines with a lot of debugging code, original was 137 lines  :-) 

One thing that I improved is that you now can zoom and pan at the same time. No PR sent yet. 

But the big issue is with the jumping when finishing a pinch-zoom. 
It has been very frustrating to debug. 

I understand that you want this fixed ASAP, me too. 
I'll let you know when I have something to show.

**Comment by stephanrauh** [comment]
@barnewsapp The other day, I found something that might help you. The method ` _setScale(value, noScroll = false)` in the file `base_viewer.js` has a second parameters that's always set to `true`. As far as I understand, you can disable scrolling by setting it to `false`. But I didn't examine it yet.

**Comment by barnewsapp** [comment]
@stephanrauh Thanks, I will look into it.

**Comment by barnewsapp** [comment]
Hi. Just a quick update on this. 
To make this work reliable, I think we have to do a bigger change than just do some changes to the pinch-on-mobile-support.ts-file. 

I think the problem is that currently the positioning of the viewer is done by using viewerContainer.scrollLeft and viewerContainer.scrolLTop. 

It would be much easier if the viewer was positioned relative with x and y. 
So my current strategy is to implement a new "module" called RelativeCoordsSupport. 
By doing it this way it is much easier to enable or disable it without breaking the current implementation. 

We are focusing on the usecase with `pageViewMode="single" scrollMode="page" spreadMode="off|even"`, because this is what we use. But I think it should work in the "normal" modes aswell. 

I'll keep you updated.

**Comment by adambeer** [comment]
@barnewsapp Any updates on this?

**Comment by barnewsapp** [comment]
Hi, Still working on it and are making some progress. 
I think using relative corrds is the way to go, but the progress is slow. 
The last two weeks I expected to have i MVP done, but no. 
I will work on it to I get it working, i can promise you that.

**Comment by barnewsapp** [comment]
Hi again. 
Okey, just had a big breakthrough :-) 
Still some work to be done and code clean up, but now I have working version locally. 

I will attach a video: 

https://user-images.githubusercontent.com/67910734/146373604-5551736b-a9cc-41b0-81cd-25ad1418c74a.MP4

PS:  I have also implemented a contain-function, if the viewer is smaller then the container, you may not pan the page outside the container.. If the viewer is bigger, you may not pan the outside the page edge.

**Comment by stephanrauh** [comment]
Sounds good! And the video looks promising, too. I'm looking forward to your solution!

**Comment by barnewsapp** [comment]
@stephanrauh @adambeer 
Hi. I will not have the time to complete the task and code clean up before Christmas. 
Should I send a PR tomorrow with my current code or wait until January when I have a fully functional version? 
Let me know what you think.

**Comment by stephanrauh** [comment]
Well, being to able to have a look at the progress in the workshop is always nice. Feel free to submit the PR, so I can have a look, and tell me when you feel it's finished.

**Comment by barnewsapp** [comment]
PR sent: #1099 
Merry Christmas

**Comment by thibaultv** [comment]
Hi,
I don't know if it could help but we add some issues with this option too (using Ionic) => Application crash/slow zoom on Android since Android Webview 97+ (or close, don't remember exactly).
We finally choose to overwrite the defaultOptions [useOnlyCssZoom](https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/bbbb56e1bc4fc5b43fda95bab80caff82b6bc0a6/projects/ngx-extended-pdf-viewer/src/lib/options/pdf-default-options.ts#L41) to "true" and it solve our issue.
Maybe it can help :)
Kr

**Comment by adambeer** [comment]
Has the PR from barnewsapp made it into the codebase yet?

**Comment by stephanrauh** [comment]
Not yet. But I started to wonder about the current state of the art, too. @barnewsapp Do you want me to merge the PR? After our last chat, I believed you still wanted to fix a bug, run a test or something like that. Did I get you wrong?

**Comment by barnewsapp** [comment]
Hi. I think we are close to a release, but where is couple of gitches (bugs) that I want to fix before it is production-ready. 

But I think it is pretty safe to merge, because it is implemented as an optional "module" that need to be enabled, and does not change any of the existing code. 
 
I hope I will have time next week to work on the last bugs.

**Comment by stephanrauh** [comment]
OK, I'll try to merge the PR this evening.

**Comment by stephanrauh** [comment]
The PR is now part of version 15.0.0-alpha.0. However, I didn't manage to publish a showcase demo yet.

**Comment by barnewsapp** [comment]
Great @stephanrauh 
Thank you.

**Comment by adamwarnick** [comment]
We had this issue and it seems to me that it hasn't been solved on the node package level. We made a temporary solution that didn't fix it 100% of the time, but was for the most part effective. 

zoomInOut: any = this.platform.is("mobile") ? "page-fit" : 100;
zoomArray = [70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200];

setZoom(zoom) {
    this.zoomInOut = Math.floor((zoom * 100) / 10) * 10;

    this.zoomArray.push(this.zoomInOut);
    this.zoomArray.splice(0, 1);

    const uniqueCount = new Set();
    for (const zoomLevel of this.zoomArray) {
      uniqueCount.add(zoomLevel);
    }
    if (uniqueCount.size < 8) {
      this.zoomInOut = 100;
    }
  }

How we got to this is we graphed the zoom data and foud that each of the 4 values was frequently repeating in a small range. So, if half or less of the possible zoom values are accounted for in a sequence, then there is a zoom issue and we reset it.

**Comment by stephanrauh** [comment]
@adamwarnick Give me some context, please. What did you do precisely? Which version of ngx-extended-pdf-viewer are you using? Did you already activate `[enableRelativeCoords]="true"`?

The cycle of four zoom values rings a bell. I've seen this, too, but I've forgotten where and when.

**Comment by stephanrauh** [comment]
@barnewsapp I've tried to implement a demo for you new feature. Unfortunately, I've run into two issues:

- Some documents render, while other don't render. The thumbnails are there. But the main window only shows the progress spinner, even after wait a long time. Adding insult to injury, there's no error message in the console window. After deactivating your flag, the document renders again. I'm puzzled. Any idea what's going wrong?
- By default, PDF files are centered. It's only the single-page mode that pins the PDF files to the left-hand side of the viewer window. If I'm not mistaken, `[enableRelativeCoords]` doesn't take centering into account.

**Comment by barnewsapp** [comment]
@stephanrauh I'll look into it next week and let you know what I find.  Any specific PDF-s that do not render?

**Comment by stephanrauh** [comment]
@barnewsapp The Portugese textbook doesn't render (Portugues-para-principiantes-1538054164.pdf). I've pushed the broken version, so all you need is cloning the showcase. I'm curious if it's just my laptop, or if it's general problem. However, I've tested both Firefox and Chromium, so my ad-blocker plugins are probably not the problem.

**Comment by adambeer** [comment]
I tested out 15.0.0-alpha.2 with [enableRelativeCoords]="true" and I cant say I see any improvements. When I pinch-zoom the document jumps all around. Im viewing a single page document also. Am I missing something to get this working?

**Comment by adambeer** [comment]
@stephanrauh So it seems that I misunderstood the scope of this fix. I can see the actual zooming action has improved, however after releasing the pinch gesture the document will still shift to a random position. Any idea what causes this or where this could be occurring?

**Comment by stephanrauh** [comment]
I'm afraid I'm clueless. I know I should investigate the topic, but at the moment new issues pop up faster than I can close them, so I'm happy to delegate the task to @barnewsapp.

**Comment by barnewsapp** [comment]
@stephanrauh @adambeer Sorry for the late reply. I'm om vacation at the moment. I'll will be back at the office next week. I'll let you know what I find.

**Comment by barnewsapp** [comment]
@stephanrauh Hi! Just a quick update from me. I've updated my branch with your latest commit (v15) and started working on the issues. 

I think I have found the reason for one of the issues when the viewer sometimes do not render. 
 `enableRelativeCoords="true" `requires `pageViewMode="single" `to be set. 

I will try to force setting that value if relative coords is enabled. 

I'll keep you updated.

**Comment by stephanrauh** [comment]
Update: @barnewsapp noticed that the canvas size seems to play a role in the glitches. In particular, if zooming causes the canvas to be larger than the browser can display, ngx-extended-pdf-viewer resets the zoom factor. Maybe that's causing the trouble.

**Comment by smout74** [comment]
Just out of curiosity: is it possible to render the pdf at max values (with: pdfDefaultOptions.maxCanvasPixels = -1;) and then use hammerjs to zoom in on that canvas as a temporary fix ?

**Comment by stephanrauh** [comment]
@smout74 Yeah, sure. That's pretty much what [pinch-on-mobile.ts](https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/main/projects/ngx-extended-pdf-viewer/src/lib/pinch-on-mobile-support.ts) does. The goal of this ticket is to make the pinch gesture feel more natural. Without `enableRelativeCoords`, the position of the fingers are ignored, so the text you're zooming scrolls away from your focus.

**Comment by smout74** [comment]
@stephanrauh I had good results with this method when I was using ng2-pdf-viewer :
https://gist.github.com/stephanbogner/06c3e0d3a1c8fcca61b5345e1af80798

But that viewer gave blurry pdf's so I switched to yours, but good pinchin is a must since users are used to do it.

**Comment by stephanrauh** [comment]
@barnewsapp I'm still short of time... can I talk you into looking at the gist of @smout74?

**Comment by smout74** [comment]
@stephanrauh I tried to re-create a small example of the zoom I used before. (only zoom, no pan or doubletap, though you can pan with 2 fingers of course)

https://github.com/smout74/pdfzoomtest.git

**Comment by adamwarnick** [comment]
@stephanrauh Sorry for the very late response, but I had made a mistake. It looks like the fix above actually solved a different issue, we didn't make further headway as far as I know.

**Comment by durgamalleswariyeruva** [comment]
@stephanrauh , I am using   [pageViewMode]="'infinite-scroll'"
    [enablePinchOnMobile]="true", [scrollMode]="0" for pdfs which contains more than one page, i am getting zoom issue when i used pinch gesture.  When i use [enableRelativeCords]='true' that made to disable vertical scrolling. 
Any solution for this will be appreciated. 

Thanks

**Comment by stephanrauh** [comment]
@TiBz0u @adambeer @cverons @smout74 @durgamalleswariyeruva @Richugan @adamwarnick and everything who's interested in this thread: The Mozilla team surprised me by implementing decent pinch-to-zoom support. Unless something unexpected happens, I'm going to remove the `enablePinchOnMobile` implementation. Probably I'll keep the attribute, but even that's subject to change.

After removing my implementation, I assume every problem you've reported is gone. The Mozilla guys approached the challenge more radically, which allowed them to provide a superior solution.

So I'm closing the ticket soon when I publish version 16 of ngx-extended-pdf-viewer.

**Comment by smout74** [comment]
NIce, looking forward to v16 !

**Comment by durgamalleswariyeruva** [comment]
@stephanrauh , I updated to latest version 16.0.2, I can still see a lit bit of jerk when i used pinch-to-zoom. jerk was happening after loader dismiss when pinch to zoom the screen. 

Is there any possible way to get rid of that issue?

Thanks

**Comment by stephanrauh** [comment]
@durgamalleswariyeruva Generally speaking, I'm sure it's possible. If your question is if I'm going to solve the issue - well, maybe, but it's not likely. First of all, I don't know what your jerk looks like precisely. Second, this is a leisure-time project, and I don't have as much leisure time as I'd like to have. But then, this is an open-source project. May I invite you to investigate the topic yourself? You'll get my support if need be, but you're the expert on your issue, so you can solve the issue easier than I can.

You need to know to things:

- add the attrbute `[minifiedJSLibraries]="false"`. This makes debugging a lot easier.
- The implementation of the pinch gesture is here: https://github.com/stephanrauh/pdf.js/blob/bleeding-edge/web/app.js#L2765-L3038
- If this looks like a lot of code: fear not. It's straight-forward. I'm sure you'll be able to wrap your head around it.

**Comment by noragarkalne** [comment]
Hello, any ideas why zoom on mobile gets crazy if I add min zoom? 
f.e. my default zoom is 70% and I don't want user to be able zoom out less than these 50% not in desktop, nor mobile version. So I tried to pass min zoom ... zoom buttons works nice but on mobile once my finger touch pdf enormous zoom in happens.

**Comment by stephanrauh** [comment]
I believe I've simply forgotten to close this ticket. If I'm wrong or if you find a related bug, please open a new ticket. That makes it easier for me to track my progress.
